name: CICD Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Train and save pipeline
      run: python train_model.py
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-trained-model
        path: trained_model
        retention-days: 2

